SELab-2/UGent-3

- backend/project/endpoints/courses/join.py
- backend/project/utils/misc.py
> Fixes several buggs in join code endpoint

- frontend/src/components/Courses/CourseDetailTeacher.tsx
> Add label to expiry date

- frontend/src/pages/project/projectView/ProjectView.tsx
> Propegating regex expressions to be checked before submitting

- backend/project/utils/submissions/evaluator.py
- backend/project/utils/submissions/evaluators/general/Dockerfile
- backend/project/utils/submissions/evaluators/general/entry_point.sh
> Creates a general code evaluator

- frontend/src/components/Courses/CourseDetailTeacher.tsx
> In join codes use dates

- backend/project/endpoints/submissions/submission_detail.py
- backend/project/endpoints/submissions/submissions.py
- backend/project/utils/authentication.py
> Submission authorization issues

- backend/project/endpoints/submissions/submission_detail.py
- backend/project/endpoints/submissions/submissions.py
- backend/project/utils/models/submission_utils.py
- backend/tests/endpoints/submissions_test.py
> Submission issues

- frontend/src/App.tsx
> Fix project path

- frontend/src/pages/project/projectOverview.tsx
closes  #286 , path was just wrong
> Fix course path

- frontend/src/components/Header/Header.tsx
> Navbar link to homepage added

- frontend/public/locales/en/translation.json
- frontend/public/locales/nl/translation.json
- frontend/src/pages/project/projectDeadline/ProjectDeadlineCard.tsx
> Fix status on ProjectCards

- frontend/index.html
> Fixed path to flavicon

- backend/project/endpoints/courses/join.py
> Corrected status code when posting but user already in course

- frontend/src/pages/error/ErrorBoundary.tsx
- frontend/src/utils/fetches/FetchMe.ts
> Added header on error pages and moved env import outside fetchme function

- backend/project/endpoints/projects/projects.py
> Check if teacher posting project is teacher of course that they're making a project for

- frontend/public/locales/nl/translation.json
- frontend/src/components/ProjectForm/ProjectForm.tsx
> When no run_tests.sh is given when creating a project, cannot submit.

- frontend/src/components/Courses/CourseUtilComponents.tsx
- frontend/src/components/Courses/CourseUtils.tsx
> Fixed bug on course detail page when deadline of projects is null

- documentation/documentation/README.md
The user guide doesn't contain a readme atm, it contains a simple one after the introduction of this PR
> Added readme for user guide

- frontend/src/components/ProjectForm/ProjectForm.tsx
Make input fields faster in project form
> Textfield performance issue

- frontend/src/components/Courses/CourseUtilComponents.tsx
> Added lang to redirect to project from courses overview

- frontend/src/pages/project/projectView/ProjectView.tsx
> Add lang path to project view redirect

- frontend/src/pages/project/projectView/SubmissionCard.tsx
> Using react mui tabs in project view instead of implementing it again

- frontend/src/components/Courses/AllCoursesTeacher.tsx
- frontend/src/components/Courses/CourseUtilComponents.tsx
- frontend/src/components/Courses/CourseUtils.tsx
> Fix flickering with data loader

- backend/seeder/seeder.py
> Seeder should generate unique submission times now

- frontend/public/locales/en/projectformTranslation.json
- frontend/public/locales/nl/projectformTranslation.json
- frontend/src/components/FolderUpload/FolderUpload.tsx
- frontend/src/components/ProjectForm/FileStructureForm.tsx
> Project form/drag drop translations

- backend/seeder/seeder.py
- frontend/src/components/Courses/CourseDetailTeacher.tsx
- frontend/src/components/Courses/CourseUtils.tsx
Reworked useEffect of admins and students Me page fetching so they dont add users twice which resulted in duplicate listing.
useEffect is always messy, moved fetching of Me objects to loader function, way better.
Fixes #234
> Teacher is now listed as admin on course page

- backend/project/init_auth.py
> Fixed JWT refresh to use database

- frontend/public/locales/en/translation.json
- frontend/public/locales/nl/translation.json
- frontend/src/App.tsx
- frontend/src/loaders/project-view-loader.ts
- frontend/src/pages/project/projectView/ProjectView.tsx
> fixed authorizations in projectview
